language: java
sudo: required
addons:
  mariadb: '10.1'
jdk:
- oraclejdk8
before_install:
- sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
- sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a
  /etc/apt/sources.list.d/commandbox.list
install:
- sudo apt-get update && sudo apt-get --assume-yes install commandbox
- box install
before_script:
before_script:
- mysql -u root -e 'create database muradb;'
- cp  requirements/tests/resources/cfapplication.cfm config/cfapplication.cfm
- box server start cfengine=luce port=53644
- curl -X POST -F 'production_domain=localhost' -F 'production_dbtype=mysql' -F 'production_datasource=muraMySQLdb' -F 'production_adminemail=matt.levine@blueriver.com'  -F 'production_username=admin'  -F 'production_password=admin' http://localhost:53644/
script: >
  testResults="$(box testbox run runner='http://localhost:53644/requirements/tests/runner.cfm' )";
  echo "$testResults";
  if grep -i "\[(Failures|Errors): [1-9][0-9]\?[0-9]\?\]\|\[Errors: [1-9][0-9]\?[0-9]\?\]\|<t[^>]*>\|<b[^>]*>" <<< $testResults;  then exit 1; fi
notifications:
    email: false
